'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GuessTheTree.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Acer_campestre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acer_campestre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Acer_platanoides() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acer_platanoides", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aesculus_hippocastanum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aesculus_hippocastanum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alnus_glutinosa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alnus_glutinosa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Betula_pendula() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Betula_pendula", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Carpinus_betulus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carpinus_betulus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fagus_sylvatica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fagus_sylvatica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fraxinus_excelsior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fraxinus_excelsior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Larix_decidua() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Larix_decidua", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Picea_abies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Picea_abies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pinus_sylvestris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pinus_sylvestris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Populus_alba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Populus_alba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pseudotsuga_menziesii() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pseudotsuga_menziesii", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Quercus_robur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Quercus_robur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Robinia_pseudoacacia1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Robinia_pseudoacacia1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Salix_alba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Salix_alba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Taxus_baccata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taxus_baccata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tilia_cordata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tilia_cordata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tree_black_silhouette_shape() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tree_black_silhouette_shape", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latin- English
        '''Abies alba - Silver fir
        '''Acer platanoides - maple
        '''Acer pseudoplatanus - sycamore
        '''Acer campestre - field maple
        '''Alnus glutinosa - Black alder
        '''Betula pendula - silver birch
        '''Betula pubescens - Downy birch
        '''Carpinus betulus - hornbeam
        '''Fagus sylvatica - beech
        '''Fraxinus excelsior - ash
        '''Larix decidua - larch
        '''Picea abies - norway spruce
        '''Pinus sylvestris - scots pine 
        '''Populus alba - 
        '''Populus tremula - aspen
        '''Pyrus communis - wild pear
        '''Pseudotsuga menziesii
        '''Quercus petraea - sessile oak
        '''Q [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property treesCheatSheet() As String
            Get
                Return ResourceManager.GetString("treesCheatSheet", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
